Repository pys-durup/CulturalCenterProject, pull requests merged in 2020-11, with the labels that each got.

#3 관리자.txt를 만들었습니다.
  CulturalCenter/src/com/project/center/employee/Employee.java
  CulturalCenter/src/com/project/center/employee/EmployeeManage.java
  CulturalCenter/src/data/관리자.txt
Labels: documentation

#4 직원 관리 기능 업데이트(1)
  CulturalCenter/src/com/project/center/employee/EmployeeAttendance.java
  CulturalCenter/src/com/project/center/employee/EmployeeManage.java
  CulturalCenter/src/com/project/center/employee/Master.java
  CulturalCenter/src/com/project/center/employee/TempMain.java
  CulturalCenter/src/com/project/center/main/Path.java
Labels: enhancement

#7 직원 관리 기능 업데이트(2)
  CulturalCenter/src/com/project/center/employee/Employee.java
  CulturalCenter/src/com/project/center/employee/EmployeeManage.java
  CulturalCenter/src/data/직원정보.txt
Labels: enhancement

#9 직원 관리 기능 업데이트(3)
  CulturalCenter/src/com/project/center/employee/EmployeeManage.java
  CulturalCenter/src/com/project/center/employee/TempMain.java
  CulturalCenter/src/data/직원정보.txt
Labels: enhancement

#12 추가
  CulturalCenter/src/com/project/center/main/CulturalCenter.java
  CulturalCenter/src/com/project/center/user/User.java
  CulturalCenter/src/com/project/center/user/UserRegister.java
Labels: enhancement

#13 직원 관리 기능 업데이트(4)
  CulturalCenter/src/com/project/center/employee/EmployeeManage.java
  CulturalCenter/src/data/직원정보.txt
Labels: enhancement

#14 추가 및 수정
  CulturalCenter/src/com/project/center/main/CulturalCenter.java
  CulturalCenter/src/com/project/center/program/ProgramManage.java
  CulturalCenter/src/com/project/center/user/User.java
  CulturalCenter/src/com/project/center/user/UserLogin.java
  CulturalCenter/src/com/project/center/user/UserRegister.java
  CulturalCenter/src/com/project/center/user/UserSelect.java
Labels: bug, enhancement

#16 직원 관리 기능 업데이트(5)
  CulturalCenter/src/com/project/center/employee/EmployeeAttendance.java
  CulturalCenter/src/com/project/center/employee/EmployeeAttendanceManage.java
  CulturalCenter/src/com/project/center/employee/EmployeeManage.java
  CulturalCenter/src/com/project/center/employee/TempMain.java
  CulturalCenter/src/data/직원정보.txt
Labels: enhancement, wontfix

#21 직원 관리 기능 업데이트(6)
  CulturalCenter/src/com/project/center/employee/EmployeeAttendance.java
  CulturalCenter/src/com/project/center/employee/EmployeeAttendanceManage.java
  CulturalCenter/src/com/project/center/employee/TempMain.java
  CulturalCenter/src/data/Path.java
  CulturalCenter/src/data/직원근태정보.txt
Labels: enhancement

#29 직원 관리 기능 업데이트(7)
  CulturalCenter/src/com/project/center/employee/EmployeeAttendanceManage.java
  CulturalCenter/src/com/project/center/employee/EmployeeManage.java
  CulturalCenter/src/com/project/center/employee/TempMain.java
  CulturalCenter/src/com/project/center/main/CulturalCenter.java
  CulturalCenter/src/com/project/center/user/User.java
  CulturalCenter/src/com/project/center/user/UserLogin.java
  CulturalCenter/src/data/직원근태정보.txt
  CulturalCenter/src/data/직원정보.txt
  CulturalCenter/src/data/회원정보.txt
Labels: documentation, enhancement

#33 직원 관리 기능 업데이트(8)
  CulturalCenter/src/com/project/center/employee/EmployeeAttendanceManage.java
  CulturalCenter/src/com/project/center/employee/EmployeeManage.java
  CulturalCenter/src/data/직원근태정보.txt
  CulturalCenter/src/data/직원정보.txt
Labels: enhancement

#39 시설예약확인 기능 추가
  CulturalCenter/src/com/project/center/faciltiy/FacilityReservation.java
  CulturalCenter/src/com/project/center/main/CulturalCenter.java
  CulturalCenter/src/data/세미나실예약.txt
  CulturalCenter/src/data/체육시설예약.txt
Labels: enhancement

#42 시설예약환불 기능 추가
  CulturalCenter/src/com/project/center/faciltiy/FacilityReservation.java
  CulturalCenter/src/com/project/center/main/CulturalCenter.java
  CulturalCenter/src/data/세미나실예약.txt
  CulturalCenter/src/data/체육시설예약.txt
Labels: enhancement
